on:
  issues:
    types: [opened, reopened]

jobs:
  label_issue_pest:
    runs-on: ubuntu-latest
    name: Pester author if they forgot to label their issue
    steps:
      - uses: crhayes/label-issue-pest@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Please add labels to your issue."
